# Generated by Django 5.2.4 on 2025-09-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_emb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='emb',
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movie/images/'),
        ),
    ]
