# Generated by Django 5.2.4 on 2025-09-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_emb_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='emb',
            field=models.BinaryField(null=True),
        ),
    ]
